dist: xenial
services:
  - docker
language: python
python:
  - "3.7"
before_install:
  - docker pull python:3
install:
  - pip install pipenv
before_script:
  - pipenv install
script:
  - pipenv run invoke test
before_deploy:
  - pipenv run pip freeze > requirements.txt
  - docker build --tag=sneakpeek .
deploy:
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  - docker tag sneakpeek "$DOCKER_USERNAME"/sneakpeek
  - docker push "$DOCKER_USERNAME"/sneakpeek
